### ISSUE TITLE
Can't use im-in.space on first launch

### ISSUE THREAD

**Issue by mkody** [glynnbird/toot#1]
I get an "Invalid input". ¯\\_(ツ)_/¯

![image](https://cloud.githubusercontent.com/assets/843787/24914497/af4790c4-1ed4-11e7-96aa-3c332ebdcf6a.png)

**Comment by glynnbird** [comment]
ah ok! I know what that is. My regular expression is too strict.

**Comment by glynnbird** [comment]
Fixed in 1.0.1
