### ISSUE TITLE
Unable to Reconfigure/Reauthorize the App

### ISSUE THREAD

**Issue by ghost** [glynnbird/toot#12]
Hi.

I installed Toot via npm in MacOS Sierra, and configured setup the app name and pointed it at my Mastodon instance, and got the token. Everything works. However, I didnt realize the name of the app would appear in the Authorized Apps page on my Mastodon account, so I decided to delete the authorization, and set up the app connection again. This is where Toot doesnt seem to work.

I retyped "toot" in the Terminal and nothing happens. I am not asked to reconfigure anything. I uninstalled and reinstalled and it doesnt seem to do anything. Also, I cant seem to understand the "-c" configuration. To my knowlege there is no configuration file.

Would you help me be able to reauthroize the app with my Mastodon instance?

Thanks.

David

**Comment by glynnbird** [comment]
Sure. 

When you run Toot for the first time, it does the authorisation dance and saves the configuration in a file `~/.mastodon.json` i.e. a a file called `.mastodon.json` in your home directory. On subsequent calls, it reads this file to post toots. 

If you want to reauth, then simply remove that file and re-run toot and it should be back to the state it was in when you first installed it.

Hope this helps.
