### ISSUE TITLE
toot not recognised on Windows 10 device

### ISSUE THREAD

**Issue by duoduoeeee** [glynnbird/toot#14]
I have a Windows 10 x64 PC with Node 8.9.0 installed. When I run "node" the outputs were all right.

I did "npm install -g toot" and got toot installed globally, but when I run "toot blablabla"  I keep getting this:

`Fatal error in launcher: Unable to create process using '"'`

I have uninstalled all python versions from my computer.

I then tried "npm install toot" and I managed to get the app working by navigating to that directory where toot is downloaded and running "node toot.bin.js".

So why is it that toot couldn't be executed globally? You know because the app is great but it needs perhaps some more elegance?

**Comment by glynnbird** [comment]
mmm. this is definitely a Windows-specific thing. I'm glad it works when you find the `toot.bin.js` file, but I'm no sure what:

> Fatal error in launcher: Unable to create process using '"'

means. I don't have a Windows machine to test it on.

**Comment by duoduoeeee** [comment]
Well I searched on the net finding it is something wrong with python. There's a Mastodon cli app for python that is also called toot. I will look into the problem.

**Comment by glynnbird** [comment]
Ah. It's possible that Windows is executing the Python 'toot' executable instead of my `toot` utility. i.e. your Python directory comes before your Node.js in the path?

**Comment by duoduoeeee** [comment]
Yeah I believe that's where the problem lies in

**Comment by duoduoeeee** [comment]
Got toot functioning properly by adjusting environment variables.

Adjust environment variable settings for both current user and system so that python goes below nodejs.

**Comment by glynnbird** [comment]
Excellent!
