### ISSUE TITLE
Add --config flag

### ISSUE THREAD

**Issue by Spunkie** [glynnbird/toot#7]
I would like to use this pkg in a CI environment, specifically appveyor, but the way `.mastodon.json` is saved makes it a bit difficult.

It would be nice if you could add a `--config` flag that would allow me to

1. pass the entire json inline
2. set the location/path of where the pkg looks for `.mastodon.json`

Allowing the json to be passed inline would let me set the contents of `.mastodon.json` as an environment variable and not have to worry about leaking my API keys anywhere.
___
So the CLI calls for these might look like 

    toot 'This is a test toot.' --config .
    toot 'This is a test toot.' --config ./some/path/to/config/file
    toot 'This is a test toot.' --config '{"domain":"mastodon.social","name":"example-app-name-v1","baseURL":"https://mastodon.social","id":4,"redirect_uri":"urn:ietf:wg:oauth:2.0:oob","client_id":"xxx","client_secret":"xxx","accessToken":"xxx"}'
    toot 'This is a test toot.' --config $Env:APPVEYOR_TOOT_AUTH_JSON

**Comment by glynnbird** [comment]
👍
